server:
  port: 7070
spring:
  application:
    name: stardust-backend
  datasource:
    url: jdbc:mysql://localhost:3306/stardust?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
# springdoc-openapi配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.philokun.stardustbackend.controller
# knife4j配置
knife4j:
  enable: true
  setting:
    language: zh_cn

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: assign-id
      logic-delete-value: 1
      logic-not-delete-value: 0

jwt:
  secret: bHjYh5oP6nQ9uKxR3s2v8w1zA7cB4eF0mG7jK5tYpFwE4iDcLqUrXaSdFbGcHeI 
  expiration: 86400000

logging:
  level:
    com.philokun.stardustbackend: info
    org.springframework: info